firstproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('', include("make_menu.urls")),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/chat", views.detail, name="chat"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/addchoice/", views.addchoice, name="addchoice"), #追加箇所
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question

from openai import OpenAI


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    chat_ans_header=""
    chat_results=""

    # 「選択肢の候補を表示する」ボタンを押した時の動き
    if request.method == "POST":
        #選択肢のデータを入手
        choice_set = []
        if question.choice_set.exists():
            for choice in question.choice_set.all():
                choice_set.append(choice.choice_text)
        else:
            choice_set = ""

        #プロンプトを定義
        prompt = "次のQuestionとChoiceを参考にして、質問（Question）に対する他の選択肢（Choice）を5つ提示してください。\n出力では引用符や括弧など、リストの構造を示す記号を除去してください。\n" + "Question:" + str(question) + "\n" + "Choice:" + str(choice_set)

        #ターミナル上にChatGPTへのプロンプトを表示させる
        print("============(ChatGPTへのプロンプト)============\n",prompt,"\n========================")

       # ChatGPT
        client = OpenAI(
            base_url = "https://api.openai.iniad.org/api/v1", #INIAD用APIエンドポイント
            api_key = "gaeB7mTywN1CBvomySitOWQZ0fhE0nHowbSf_91CRp3WbpVGt7WoiYDG4Ie5FLO45_4SxaUuQRfY8yXjATMTAhQ", #自身のAPIキーを貼り付け
        )
        response = client.chat.completions.create(
            model="gpt-4o-mini", #3.5-turboでも動くが、INIADが本モデルを推奨

            messages=[
                {
                    "role": "system",
                    "content": "日本語で応答してください。可能な限り少ない文字数で回答してください。"
                },
                {
                    "role": "user",
                    "content": prompt
                },
            ],
        )

        #ChatGPTの出力結果
        chat_ans_header = 'ChatGPTによる他の選択肢の候補'
        chat_results = response.choices[0].message.content

    context = {
        "question": question,
        'chat_results': chat_results,
        'ans_header': chat_ans_header
    }
    return render(request, "polls/detail.html", context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "ラジオボタンを選択してください",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


#↓追加箇所
def addchoice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        question.choice_set.create(choice_text=request.POST.get('add'), votes=0)
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))

    else:
        return render(request, "polls/addchoice.html", {"question": question})

polls/templates/polls/addchoice.html
<p>
    <a href="{% url 'polls:detail' question.id %}">投票画面に戻る</a>
</p>

<h1>選択肢を追加する</h1>

<h3>質問項目</h3>

<div>{{question.question_text}}</div>

<h3>現在の選択肢</h3>
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>

<form action="{% url 'polls:addchoice' question.id %}" method="post">
    <div>
        <label for="addchoice">追加する選択肢</label>
        {% csrf_token %}
        <input type="text" name="add">
        <button type="submit">追加</button>
    </div>
</form>

polls/templates/polls/detail.html
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ question.question_text }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-jLKHWM3OQd4Fw+1XYvZZo+P8qoKL+m0Kd1mUWHTDbSO4F8U4QqVUB+ZTjRiBP7k+" crossorigin="anonymous">
</head>
<body>
    <p>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>
        <a href="{% url 'polls:index' %}">質問に戻る</a>
    </p>
    

    
    
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
    
        <nav class="navbar navbar-light " style="background-color: #e3f2fd;">
            <div class="container-fluid" style="justify-content: space-around">
                <span class="navbar-brand mb-0 h1">{{ question.question_text }}</span>
            </div>
        </nav>
    
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
        <p class="text-center mb-0" style="background-color: #e3f2fd;">ラジオボタンを1つ選択し、投票しましょう！</p>
        
        <div class="ps-5 py-3" style="background-color:antiquewhite">
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </div>
    

    
        <div style="display:flex; justify-content: space-evenly; padding-top: 10px;">
            <input type="submit" value="投票する">
                    <!-- ボタンの追加 -->
            <a style="text-decoration:none; background-color: buttonface; color: buttontext; padding-block: 3px; padding-inline: 9px; border-width: 1px; border-style: outset; border-color: buttonborder; border-image: initial; border-radius: 3px;"
            href="{% url 'polls:addchoice' question.id %}" >選択肢を追加する</a>
            
        </div>
    
    </form>
    
    <div>
        <form action="{% url 'polls:chat' question.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="upvote" value="選択肢の候補を表示する">
        </form>
        <p>＊ChatGPTが他の選択肢の候補を出してくれます</p>
        <h4>{{ ans_header }}</h4>
        <p>{{ chat_results }}</p>
    </div>
</body>
    
</html>

polls/templates/polls/index.html
<!doctype html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Let's Vote!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <nav class="navbar navbar-light " style="background-color: #e3f2fd;">
        <div class="container-fluid" style="justify-content: space-around">
            <span class="navbar-brand mb-0 h1">Django-投票アプリケーション</span>
        </div>
    </nav>

</head>

<body>

    {% if latest_question_list %}
    {% for question in latest_question_list %}
    <div class="list-group">

        <!-- ブロックを中心に表示、幅を25%に固定、上下に余白を設定、テキストを中央揃えにする -->
        <div class="mx-auto w-25 my-2 text-center">
            <a href="{% url 'polls:detail' question.id %}"
                class="list-group-item list-group-item-action list-group-item-primary" style="border-radius: 4%">{{ question.question_text}}</a>
        </div>

    </div>
    {% endfor %}
    {% endif %}

</body>

</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">もう一度投票する</a>