firstproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('', include("make_menu.urls")),
]

make_menu/urls.py
from django.urls import path
from . import views

app_name = "make_menu"
urlpatterns = [
   path("", views.index, name="index"),
   path("result/", views.result, name="result"),
   path("read_csv/", views.read_csv, name="read_csv"),
   path('db/create/', views.create, name='create'),
   path('db/add/', views.add_text, name='add_text'),
   path('db/read/', views.read_text, name='read_text'),
   path('scrape/', views.scrape, name='scrape'),

]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/chat", views.detail, name="chat"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/addchoice/", views.addchoice, name="addchoice"), #追加箇所
]

make_menu/models.py
from django.db import models

class Average(models.Model):
    code = models.CharField(max_length=6, unique=True)  # 重複のない単一の6桁のコード
    name = models.CharField(max_length=100)  # 野菜の名前（漢字、ひらがな、カタカナ）
    g_per_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    # 各月の価格、値がない場合は0にする
    price_01 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_02 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_03 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_04 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_05 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_06 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_07 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_08 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_09 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_10 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_11 = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    price_12 = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.name} ({self.code})"

make_menu/views.py
from django.shortcuts import render, redirect
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI

import csv
from .models import Average
from django.http import HttpResponse
from django.conf import settings

from .function.scrape import scrape_cookpad
from .function.db import create_chroma, read_text_chroma, add_text_chroma
from .function.func import diff


# Create your views here.
def index(request):
    # 冷蔵庫DBから食材を取得
    ingredientsInRefrigerator = ["ニンジン", "玉ねぎ", "レタス"]
    
    # (API-平均)の値を返す
    CheaperFoods = diff()
    
    request = request
    context = {"text": "arrot",
        "refrigerator": ingredientsInRefrigerator,
        "cheaper": CheaperFoods,
    }
    return render(request, "make_menu/index.html", context)
    
    
def result(request):
    context = ""
    if request.method == 'POST':
        cheaper = request.POST.get('select_cheaper')
        ingredients = request.POST.get('select_ingredients')
        question = request.POST.get('detail')
        
        query = cheaper + question + question
        recipe = read_text_chroma(query)
        
        # .envファイルの内容を読み込みます
        load_dotenv()
        
        
        # LLMを定義。今回はChatGPTの4o-miniを利用する
        llm = ChatOpenAI(
            model_name="gpt-4o-mini",
            temperature=0,
            openai_api_base= os.getenv("URL"),
            openai_api_key = os.getenv("OPEN_API_KEY"),
            verbose=True
            )
        
        template = """以下の食材とdetailに沿った献立を考えてください。
        安くなっている食材: {cheaper}
        冷蔵庫の中の食材: {ingredients}
        detail: {question}
        食材はなるべく多く使用してください。
        これらのレシピも必要であれば、使用してください。
        {recipe}
        """
        
        Input = """回答のフォーマットは以下のようにしてください。料理を３つ提案してください。
        ----
        料理名:料理名
        使用する食材：使用する食材1(冷蔵庫の中にあるor例年より何円安くなっているか)
                  使用する食材2(冷蔵庫の中にあるor例年より何円安くなっているか)
    
        作り方：1. 手順1
               2. 手順2
    
        特徴：子供でも食べやすい、ヘルシー、夏バテ解消など
        ----
        見やすくするための空白行
        """
        response = llm.invoke(template.format(cheaper=cheaper, ingredients=ingredients, question=question, recipe=recipe))
        
        output_by_simple_llm = response.content
        
        print(type(response))
        print(type(output_by_simple_llm))
        print(output_by_simple_llm)
        
        context = {
            "res": output_by_simple_llm,
        }

    return render(request, 'make_menu/result.html', context)

    
    
def read_csv(request):
    # プロジェクトのベースディレクトリを取得
    base_dir = settings.BASE_DIR
    file_path = os.path.join(base_dir, "make_menu", "csv", "merged_avg.csv")
    
    try:
        with open(file_path, newline="", encoding="utf-8") as csvfile:
            reader = csv.reader(csvfile)
            next(reader)  # ヘッダーをスキップ
            for row in reader:
                if len(row) < 14:
                    return HttpResponse(f"CSVファイルの行に不足している列があります。行: {row}")
                
                # 空文字列を0に変換
                def to_decimal(value):
                    return float(value) if value else 0
                
                # 新規作成または更新
                Average.objects.update_or_create(
                    code=row[0],
                    defaults={
                        'name': row[1],
                        'g_per_price': to_decimal(row[2]),
                        'price_01': to_decimal(row[3]),
                        'price_02': to_decimal(row[4]),
                        'price_03': to_decimal(row[5]),
                        'price_04': to_decimal(row[6]),
                        'price_05': to_decimal(row[7]),
                        'price_06': to_decimal(row[8]),
                        'price_07': to_decimal(row[9]),
                        'price_08': to_decimal(row[10]),
                        'price_09': to_decimal(row[11]),
                        'price_10': to_decimal(row[12]),
                        'price_11': to_decimal(row[13]),
                        'price_12': to_decimal(row[14]),
                    }
                )
            return HttpResponse("CSVファイルのインポートに成功しました。")
    except FileNotFoundError:
        return HttpResponse("指定されたCSVファイルが見つかりませんでした。")

def create(request):
        result = create_chroma()
        message = result["status"] +":"+ result["message"]
        return HttpResponse(message)


def add_text(request):
    text = []
    try:
        base_dir = settings.BASE_DIR
        recipe_dir = os.path.join(base_dir, "make_menu", "recipe2")  # recipe2フォルダを指定

        # recipe2フォルダ内の全てのファイルを取得
        for file_name in os.listdir(recipe_dir):
            file_path = os.path.join(recipe_dir, file_name)

            # ファイルかどうかを確認（ディレクトリが含まれている可能性があるため）
            if os.path.isfile(file_path):
                with open(file_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        text.append(line)

        # 処理したテキストを使って、次の処理を行う
        result = add_text_chroma(text)
        message = result["status"] + ":" + result["message"]
        return HttpResponse(message)
    
    except FileNotFoundError:
        return HttpResponse("指定されたtextファイルが見つかりませんでした。")


def read_text(request):
    text = "とまととチーズを使った。子供が喜ぶクリスマス料理"
    result = read_text_chroma(text)
    print(result)
    return HttpResponse(result)
    
    
def scrape(request):
    if request.method == 'POST':
        # フォームから入力されたテキストを取得
        input_text = request.POST.get('input_text')
        
        if input_text:
            # スクレイピング関数を呼び出し
            scraped_recipes = scrape_cookpad(input_text)
            
            if scraped_recipes:
                # 各要素をHTMLとしてテンプレートに渡す
                return render(request, 'make_menu/scrape.html', {'recipes': scraped_recipes})
            else:
                return render(request, 'make_menu/scrape.html', {'error': 'データが取得できませんでした。'})
    
    # フォームを表示
    return render(request, 'make_menu/scrape.html')

make_menu/templates/make_menu/index.html
<!doctype html>
<html lang="ja">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Let`s make menu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="/firstproject/make_menu/static/make_menu/style.css">

    <style>
        /* 全体のスタイル調整 */
        body {
            font-family: 'ヒラギノ角ゴシック';
            background-color: #ffffff;
            color: #4C4C4C;
            padding: 20px;
            margin: 0;
            font-weight: 700;
            font-style: normal;
            font-size: 16px;
        }

        h5 {
            font-weight: bold;
            margin: 0;
            padding-top: 25px;
            padding-left: 0px; 
            padding-bottom: 5px;
        }

        h6 {
            font-family: 'serif';
            font-size: 12px;
            font-weight: bold;
            line-height: 1.4;
        }

        /* 画像とテキストを横並びにするためのスタイル */
        .image-text-container {
            display: flex;
            align-items: center;
        }

        /* パソコン版のスタイル（デフォルト） */
        @media (min-width: 577px) {
            body {
                padding-left: 20%;
                padding-right: 20%;
            }
        }
        
        .ingredient-selection {
            margin: 20px 0;
            font-size: 30px;
        }

        /* 詳細情報入力欄のスタイル */
        input[name="detail"] {
            width: 100%;
            padding: 10px;
            border-radius: 5px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        /* 食材のスタイル */
        .food-item {
            display: inline-block;
            padding: 10px;
            margin: 5px;
            background-color: #F6B352;
            color: white;
            border-radius: 50px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            border: none;
            outline: none;
            font-weight: normal;
            box-shadow: 0 4px #9f6b22;
        }

        .food-item:active {
            box-shadow: 0 2px #9f6b22;
            transform: translateY(2px); /* 要素が少し下に動く */
        }

        .food-item.selected {
            background-color: #f39410;
            box-shadow: 0 2px #9f6b22; /* 押し込まれた状態の影 */
            transform: translateY(2px); /* 押し込まれた状態 */
        }

        /* 横並びで折り返すスタイル */
        .food-container {
            display: flex;
            flex-wrap: wrap;
            gap: 5px; /* 要素間のスペースを調整 */
        }

        /* ボタンのスタイル */
        .submit-button {
            background-color: #F6B352;
            color: white;
            border: none;
            padding: 0px;
            font-size: 1rem;
            cursor: pointer;
            border-radius: 50px;
            transition: background-color 0.3s ease;
            display: block;
            width: 100%;
            margin-top: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding-bottom: 5px;
            padding-top: 5px;
        }

        .submit-button:hover {
            background-color: #32CD32;
            padding-bottom: 5px;
            padding-top: 5px;
        }
    </style>

    <script>
        function toggleInputValue(element, foodName, inputFieldId) {
            var inputField = document.getElementById(inputFieldId);
            var currentValue = inputField.value.trim();
            var foodList = currentValue ? currentValue.split(',') : [];

            const index = foodList.indexOf(foodName);
            const isSelected = element.classList.contains('selected');

            if (isSelected) {
                if (index > -1) {
                    foodList.splice(index, 1);
                }
                element.classList.remove('selected');
            } else {
                if (index === -1) {
                    foodList.push(foodName);
                }
                element.classList.add('selected');
            }

            inputField.value = foodList.join(',').trim();
        }
    </script>
</head>

<body>
    <div class="image-text-container">
        <img src="{% static 'make_menu/20240905150859.png' %}" alt="My image" width="35" height="50">
        {% if text %}
        <h5>{{ text }}</h5>
        {% endif %}
    </div>

    {% if refrigerator  %}
    <form action="{% url 'make_menu:result' %}" method="post">
        {% csrf_token %}

        <p class="ingredient-selection">食材を選んでください。</p>

        <p>例年より安い食材</p>
        <input type="hidden" id="input1" name="select_cheaper" value="">
        <div class="food-container">
            {% for food in cheaper %}
            <span class="food-item" data-selected="false" onclick="toggleInputValue(this, '{{ food.0 }}', 'input1')">{{ food.0 }}:{{ food.1 }}円</span>
            {% endfor %}
        </div>

        <br />

        <p>冷蔵庫の中にある食材</p>
        <input type="hidden" id="input2" name="select_refrigerator" value="">
        <div class="food-container">
            {% for food in refrigerator %}
            <span class="food-item" data-selected="false" onclick="toggleInputValue(this, '{{ food }}', 'input2')">{{ food }}</span>
            {% endfor %}
        </div>

        <br />

        <label for="input3">リクエストを入力してください</label>
        <input type="text" id="input3" name="detail">

        <br />
        <br />

        <h6>
            たとえば...<br />
            「家族で楽しめるパーティ料理」<br />
            「胃が痛いので胃に優しい料理」<br />
            「じゃがいも使い切りレシピ」<br />
        </h6>

        <button type="submit" class="submit-button">送信</button>
    </form>
    {% endif %}
</body>

</html>

make_menu/templates/make_menu/result.html
<!doctype html>
<html lang="ja">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../../static/make_menu/result.css">

    <title>Result Page</title>
    <link rel="stylesheet" href="/firstproject/make_menu/templates/make_menu/css/result.css">
    <style >
        .image-text-container {
            display: flex;
            align-items: center;
            padding: 0 0 0 10vw;
        }
        
        h5 {
            font-weight: bold;
            margin: 0;
            padding-top: 25px;
            padding-left: 0px; 
            padding-bottom: 5px;
        }
    </style>
</head>

<body>
    <div class="image-text-container" >
        <img src="{% static 'make_menu/20240905150859.png' %}" alt="My image" width="35" height="50">
        <h5>arrot</h5>
    </div>

    {% if res %}
    <div class="container">
        {{ res|safe }}
    </div>
    {% else %}
    <h1>No Data</h1>
    <p>No input data was provided.</p>
    {% endif %}

</body>

</html>

make_menu/templates/make_menu/scrape.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>フォームページ</title>
</head>
<body>
    <h1>テキストを入力してください</h1>
    <form method="post">
        {% csrf_token %}
        <label for="input_text">料理を検索してください:</label>
        <input type="text" name="input_text" id="input_text">
        <button type="submit">検索</button>
    </form>
    <div>
        {% if recipes %}
            <h2>検索結果:</h2>
            <ul>
            {% for recipe in recipes %}
                <li>{{ recipe|safe }}</li>
            {% endfor %}
            </ul>
        {% elif error %}
            <p>{{ error }}</p>
        {% else %}
            <p>検索結果がありません。</p>
        {% endif %}
    </div>
</body>
</html>